---

 hd_version: 3.1.2

 hadoop_version: "{{ hd_version | replace('.','_')}}"

 name: hadoop

 hadoop_root_dir: /opt/hadoop

 groupname: hadoop

 hadoop_url: https://archive.apache.org/dist/hadoop/common/{{ name }}-{{ hd_version  }}/{{ name }}-{{ hd_version  }}.tar.gz

 hdfs_username: hdfs

 yarn_username: yarn

 mapred_username: mapred

 nfs_username: nfsserver

 dirs:
   - /opt/hadoop
   - /opt/hdfs

 JAVA_HOME: $(readlink -f /usr/bin/java | sed "s:/jre/bin/java::")

 HADOOP_HOME: "{{hadoop_root_dir}}/{{ name }}-{{ hadoop_version }}"

 PATH: "$PATH:{{ HADOOP_HOME }}/bin:{{ HADOOP_HOME }}/sbin"

 HADOOP_CONF_DIR: "{{ HADOOP_HOME }}/etc/hadoop"

 HDFS_HOME: "{{ hadoop_root_dir }}/hdfs"

 KDC_REALM: "{{ KDC_REALM }}"

 KDC_KEYTAB: "/etc/security/{{ KDC_REALM }}/keytab"

 HDFS_NAME_DIR: "{{ HDFS_HOME }}/name"

 HDFS_DATA_DIR: "/mnt/data"

 TRUSTSTORE_DIR: /etc/security/serverKeys

 TRUSTSTORE_FILE_LOCATION: "{{ TRUSTSTORE_DIR }}/hadoop.truststore"

 TRUSTSTORE_PASSWORD: "{{ truststorepassword }}"

 KEYSTORE_FILE_LOCATION: "{{ TRUSTSTORE_DIR }}/{{ ansible_hostname }}.keystore"

 KEYSTORE_PASSWORD: "{{ truststorepassword }}"

 APP_LOGS_DIR: "/opt/applogs"

 APP_CONF_DIR: "/opt/appconf"

 APP_LIB_DIR: "/opt/applib"

 TEMPLATE_FILENAMES:
    - core-site.xml
    - hdfs-site.xml
    - mapred-site.xml
    - ssl-client.xml
    - ssl-server.xml
    - yarn-site.xml

 users:
    - "{{ hdfs_username }}"
    - "{{ yarn_username }}"
    - "{{ mapred_username }}"
    - "{{ nfs_username }}"

 TMP_DIRS:
    - /tmp/hadoop-yarn/nm-local-dir/filecache
    - /tmp/hadoop-yarn/nm-local-dir/usercache

 MASTER_NODE: "{{ groups['masternode_group']|map('extract', hostvars, ['inventory_hostname'])|list|first }}"

 HDFS_NODE: "hdfs://{{ groups['masternode_group']|map('extract', hostvars, ['inventory_hostname'])|list|first }}:8020"

 zookeeper_ips: |
                {% set comma = joiner(",") %}{% for host in groups['zookeepersnode_group'] -%}{{ comma() }}{{ hostvars[host].ansible_host }}{%- endfor -%}
