---
      - name: get an IP addres from the hostname required for deleting/removing DNS entry.
        set_fact: ipaddress="{{ hostvars[inventory_hostname].ansible_host }}"

      - debug:
          msg: "Add logic for firing DNS API ( use CURL or get module ) for deleting DNS entry by passing inventory_hostname as fqdn and ipaddress as input"
