---

- name: FileBeat Yum Repository
  copy:
    dest="/etc/yum.repos.d/filebeat-5.x.repo"
    content="{{filebeat_yum_config}}"
    owner="root"
    group="root"
    mode="0644"
  when: filebeat_use_repo

- name: Install FileBeat (RedHat)
  yum:
    state="{{ (filebeat_upgrade) | ternary('latest', 'present') }}"
    name="{{item}}"
    update_cache=yes
  with_items: "{{filebeat_packages}}"
  notify: filebeat restart
  when: filebeat_use_repo

- name: Download FileBeat RPM
  get_url:
    url: "{{filebeat_package_baseurl}}/{{item}}-{{filebeat_version}}-{{ansible_architecture}}.rpm"
    dest: "/var/cache/yum/{{ansible_architecture}}/{{item}}-{{filebeat_version}}-{{ansible_architecture}}.rpm"
  with_items: "{{filebeat_packages}}"
  when: not filebeat_use_repo

- name: Install FileBeat from RPM
  yum:
    name: "{{ filebeat_custom_url }}/{{item}}-{{filebeat_version}}-{{ansible_architecture}}.rpm"
    state: present
  with_items: "{{filebeat_packages}}"
  notify: filebeat restart
  when: not filebeat_use_repo

# vi:ts=2:sw=2:et:ft=yaml
